apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  labels:
    cloud.googleapis.com/location: southamerica-east1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/minScale: '0'
    run.googleapis.com/max-surge: '0'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:     
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 197343799268-compute@developer.gserviceaccount.com
      containers:
      - name: backend
        image: southamerica-east1-docker.pkg.dev/oficina-facil-prd/fiap-docker/backend:latest
        ports:
        - name: http1
          containerPort: 3000
        env:
          - name: DATABASE_URL
            value: mongodb+srv://fiaptcgrupo22:mongo2024@serverlessinstance0.25wwxch.mongodb.net/?retryWrites=true&w=majority&appName=ServerlessInstance0
          - name: MERCADOPAGO_URL
            value: https://api.mercadopago.com/
          - name: MERCADOPAGO_USERID
            value: 84967632
          - name: MERCADOPAGO_TOKEN
            value: TEST-2407420594039251-030222-bec9539a6ba5cae720b4f6d07ad3bd7a-84967632
          - name: MERCADOPAGO_POS
            value: SUC001
          - name: MERCADOPAGO_WEBHOOK_URL
            value: http://fiap.com.br     
          - name: TOKEN_PRIVATE_KEY
            value: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCsujZg/Fxhytbh\nIbpMF8n/ExSv4ZKPhAiWsfUXvAyhRZrkjCX2Kd3a/1xRZY5myZS+A1RG4Uzv+UTY\nEdoNvypHsqySu7K6MRDuSNoPF5BslbH0cmsPeLXuMX2Oty644JrpTDS34WnUbnoT\nskUyeoJPtX1eaMnRn5b9mrWhMkFlLZHiMmefHwcno+/nd3p0/Se8+tFi9W4ZRD2f\nVFezAz6UfM9ixf6G1sHX/II+C5hj8nj/viiSDDsn/+M89uAfxcHxSrnyfKj15glm\n+A9FaFMYFtHt4cgb5G2cADQb03q/5V2cjASL+527fjVZbdA+LfxBqaTX2UOUlrry\n3MaNXtcjAgMBAAECggEAGJu7DZxGqSQV8yM0AI1PGQkl5Fz13X6JHrch3QzMm9ln\n1PHmoqiaVA4Xn/0hCaHkkCG3SxXkOThBR6tbbqPyqR5amdkmAILnD5vPfWD1EZNO\nNC5s9FpVSSdB5ShR/sL5Lw3NYPk7c6l9uPqoAyYTFLodr2qsfjIHeAAnqlyXloto\nOlIax4CxeekuiHJ3lTouIHe86+4naKg/kGfLojMYreW114ch7EWtyXIGOgCE57e6\ny4cRcov39DQ4taSioqcb2rZ8Ehh+FxDIolRdntecJOKgZdHik3Ag8jIhge8qfJby\n8Vn+GiCYRwtINTOql+QM+ettA7VhnTOzBti7tDaTiQKBgQDqv0JYjTexrGKyGD4C\nNgahgkRgCocvI0C41L1nJeJewj/CMaaXRxH8hICt3Y2pvWyP8Ys2ci9rDOhwXMQH\n1LiaGkkPrhtOTIL5fLbaugJe0OhQfuKNUlWO9i8rY1/nDad68PWxZW0FttCUVknS\nBUiIq8ffEU53Vf29ha6egdzzvwKBgQC8XYU8gxJFUNlQ2Pw3r3b3johXvw2r0JkM\noO6e5rWzka+xR+hWBQXw+MpyB08M4sUfK9BhJlJd4Of9qxu5W6VrkRTyHP4tynTP\nScdAk0LHDXIxQG8OVY+8jvmz6lxetFBEpzrDq4OknOn39+AVtDs30MOrbGGwkGBW\nqA2KpA1lnQKBgQDQEbCT3q/T2xEr/FLSEOL1uwox+oLyJBQU//PVfn3UMebjkLCx\ne7wUj7mi4jLTleOo/pa/LpybDTjlh0P2EPWDGfNSY6cuUqDw1DsbSi4Zrp+L4bub\nObQ+YDVVBuMVYEPns7aCg30LyIu+P3F1J1uwUFp7fNKI8f5TQy+QrViT7wKBgQCN\nZ29T49lda7oX9Swx6WjXooo7xNLQfoHGdzFq3CrfKKjJ3v9NQ+wX38yqGU6Aj+QG\n6G8/3vLKQsIlLcRcO65Mt9cPgjBV07wouGv50BK7Nx7YVlSIYDbNCE/vfinldlsj\njp6QsTrb4mfJnKz93hTua6vYDj6vu1J2+yVfRJRCCQKBgAxdt89OQsYAnQKeIYOj\nSovV1QPOqIuQollPCyADYDZQgeg0HInepWJCFk1PAGHitPJvpk4cj7Vfy0XkgkAT\nYCB+W6qVBJxTgHb9308W33hX8VFAaMw9omeBQ6YQnhxZ784PDt7PYMXSZ9LYPOtj\n1RGutxJ1c4ZdmQPKSLlS3Yjw\n-----END PRIVATE KEY-----\n"
        resources:
          limits:
            cpu: '1000m'
            memory: '1Gi'
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true